# Generated by Django 5.2 on 2025-05-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Subjects',
        ),
        migrations.CreateModel(
            name='DifferentSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('differntsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='PopularSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('popularsubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentsubjects')),
            ],
        ),
        migrations.CreateModel(
            name='ToprelatedSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('toprelatedsubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentsubjects')),
            ],
        ),
    ]
