# Generated by Django 5.2 on 2025-05-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_courses_subjects_differentsubjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='differentsubjects',
            old_name='differntsubject',
            new_name='subject',
        ),
    ]
