# Generated by Django 5.2 on 2025-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_differntsubject_differentsubjects_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularsubjects',
            old_name='popularsubjects',
            new_name='trending1',
        ),
        migrations.RenameField(
            model_name='toprelatedsubjects',
            old_name='toprelatedsubjects',
            new_name='trending2',
        ),
    ]
