# Generated by Django 5.2 on 2025-05-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_popularsubjects_popularsubjects_trending1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularsubjects',
            old_name='trending1',
            new_name='popsub',
        ),
        migrations.RenameField(
            model_name='toprelatedsubjects',
            old_name='trending2',
            new_name='topsub',
        ),
    ]
