# Generated by Django 5.2 on 2025-05-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_trending1_popularsubjects_popsub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloadmaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pop_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.popularsubjects')),
                ('top_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.toprelatedsubjects')),
            ],
        ),
    ]
