# Generated by Django 5.2 on 2025-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_downloadmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularsubjects',
            name='files',
            field=models.FileField(default='default.pdf', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toprelatedsubjects',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='downloadmaterials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
