# Generated by Django 5.2 on 2025-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_popularsubjects_files_toprelatedsubjects_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toprelatedsubjects',
            old_name='files',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='popularsubjects',
            name='files',
        ),
        migrations.AddField(
            model_name='popularsubjects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='popularsubjects',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='popularsubjects',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='popularsubjects',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='toprelatedsubjects',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='toprelatedsubjects',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='toprelatedsubjects',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
