# Generated by Django 5.2 on 2025-05-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_files_toprelatedsubjects_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exams')),
            ],
        ),
        migrations.CreateModel(
            name='PopularExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('popexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentexams')),
            ],
        ),
        migrations.CreateModel(
            name='ToprelatedExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('topexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentexams')),
            ],
        ),
    ]
