# Generated by Django 5.2 on 2025-05-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_exams_differentexams_popularexams_toprelatedexams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('popcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentcourses')),
            ],
        ),
        migrations.CreateModel(
            name='ToprelatedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('topecourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentcourses')),
            ],
        ),
    ]
