# Generated by Django 5.2 on 2025-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_courses_differentcourses_popularcourses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('wnumber', models.CharField(max_length=15)),
                ('pnumber', models.CharField(max_length=15)),
                ('cmode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=10)),
            ],
        ),
    ]
